### ISSUE TITLE
What Is The Version of Tensorflow or Keras？

### ISSUE THREAD

**Issue by CharlotteYang12** [fferroni/PointPillars#4]
Hello，I‘ve get error msg：
Traceback (most recent call last):
  File "point_pillars_training_run.py", line 52, in <module>
    workers=1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 2312, in fit_generator
    callbacks.on_epoch_begin(epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/callbacks.py", line 80, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/callbacks.py", line 596, in on_epoch_begin
    lr = self.schedule(epoch)
TypeError: <lambda>() missing 1 required positional argument: 'lr'

Could u please tell us the right version ？

**Comment by lawrencekiba** [comment]
was looking for this as well.

**Comment by tyagi-iiitv** [comment]
Code to setup this repo: https://link.medium.com/TVNzx03En8

**Comment by tyagi-iiitv** [comment]
An updated version of this repo: https://github.com/tyagi-iiitv/PointPillars.
