### ISSUE TITLE
how to setup

### ISSUE THREAD

**Issue by sdu2011** [fferroni/PointPillars#8]
when i run 
```
python setup.py build
```
it outputs
```
(tf1.15) sc@sc:~/disk/git/PointPillars$ python setup.py build
running build
running build_ext
CMake Error at CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/sc/disk/git/PointPillars/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:4 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/home/sc/disk/git/PointPillars/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    zip_safe=False,
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 33, in run
    self.build_extension(ext)
  File "setup.py", line 57, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/sc/anaconda3/envs/tf1.15/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/sc/disk/git/PointPillars', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/sc/disk/git/PointPillars/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/home/sc/anaconda3/envs/tf1.15/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

how to solve this?

**Comment by scrouzet** [comment]
You need to clone the repo with submodules:
```bash
git clone https://github.com/fferroni/PointPillars.git --recurse-submodules
```

**Comment by tyagi-iiitv** [comment]
I wrote an article on how to setup this code: https://link.medium.com/TVNzx03En8

**Comment by tyagi-iiitv** [comment]
Latest maintained repo of this code: https://github.com/tyagi-iiitv/PointPillars.
